# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: gke-test
  # namespace: gke-test-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gke-test
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: gke-test
    spec:
      serviceAccountName: sql-user
      containers:
      - name: cloud-sql-proxy
        # It is recommended to use the latest version of the Cloud SQL proxy
        # Make sure to update on a regular schedule!
        image: gcr.io/cloudsql-docker/gce-proxy:1.17
        command:
          - "/cloud_sql_proxy"

          # If connecting from a VPC-native GKE cluster, you can use the
          # following flag to have the proxy connect over private IP
          - "-ip_address_types=PRIVATE"

          # Replace DB_PORT with the port the proxy should listen on
          # Defaults: MySQL: 3306, Postgres: 5432, SQLServer: 1433
          - "-instances=e2eechat-apurer:europe-west4:test-database=tcp:3306"
        securityContext:
          # The default Cloud SQL proxy image runs as the
          # "nonroot" user and group (uid: 65532) by default.
          runAsNonRoot: true
          allowPrivilegeEscalation: false
      - name: gke-test
        image: gcr.io/PROJECT_ID/IMAGE:TAG
        ports:
        - containerPort: 8443
          protocol: TCP
        - containerPort: 7331
          protocol: TCP
        volumeMounts:
          - name: tls
            mountPath: /etc/tls
            readOnly: true
        securityContext:
          allowPrivilegeEscalation: false
          runAsUser: 5777
        env:
          - name: TCP_SERVER_PORT
            value: "7331"
          - name: HTTP2_SERVER_PORT
            value: "8443"
          - name: TLS_CERT
            value: /etc/tls/tls.crt
          - name: TLS_KEY
            value: /etc/tls/tls.key
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: db
                key: username
          - name: DB_PASS
            valueFrom:
              secretKeyRef:
                name: db
                key: password
          - name: DB_NAME
            valueFrom:
              secretKeyRef:
                name: db
                key: database
          - name: DB_PORT
            valueFrom:
              secretKeyRef:
                name: db
                key: port
          - name: DB_HOST
            valueFrom:
              secretKeyRef:
                name: db
                key: host
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 100m
      volumes:
        - name: tls
          secret:
            secretName: yourdomain-tls
