apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: gke-test-deny-external-egress
spec:
  podSelector:
    matchLabels:
      app: gke-test
  policyTypes:
  - Egress
  egress:
  - ports:
    - port: 8443
      protocol: TCP
  - to:
    - namespaceSelector: {}